# Generated by Django 3.2.12 on 2022-02-09 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.CharField(max_length=200)),
                ('expiration_date', models.DateTimeField()),
                ('barcode', models.CharField(max_length=200, unique=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.transaction')),
                ('payment_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payables.paymentstatus')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payables.servicetype')),
            ],
        ),
    ]
