# Generated by Django 3.2.12 on 2022-02-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payable',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
