# Generated by Django 3.2.12 on 2022-02-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0003_alter_payable_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payable',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=6),
            preserve_default=False,
        ),
    ]
